### ISSUE TITLE
Doc says Java 8 is required but I thought Android says Java 7

### ISSUE THREAD

**Issue by kellyfj** [segmentio/analytics-android#214]
Pretty sure Android still supports up to JDK 7 https://source.android.com/source/initializing.html but not 8 yet?

**Comment by f2prateek** [comment]
Java 7 is needed to assemble the SDK since we use diamond operators. The Java 8 requirement is for some of the JSON tests that are currently dependent on the ordering of map elements, which differs between Java 7 and Java 8. 

This doesn't affect consumers since you can use  the newer Java 7 language features (other than try with resources) on older devices. http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Using-sourceCompatibility-1.7

**Comment by f2prateek** [comment]
Updated the ready to reflect this.
