### ISSUE TITLE
There should be a way to know if flush() failed

### ISSUE THREAD

**Issue by bryant1410** [segmentio/analytics-android#463]
There's the `flush()` operation to trigger the action of uploading pending events tracked. Isn't there a way to know if it didn't succeed? It will be nice to have it. I understand this is not a pretty common use case.

**Comment by f2prateek** [comment]
Could you explain your use case? We can't really add it now without breaking the API for integrations, but I'd like to keep it in consideration for the next major release.

Additionally, this is hard since most of the SDKs we integrate with don't have a callback in their libraries to indicate when the flush completes.

If you're only interested in the flush to segment servers, your best option for now is to use a custom connection factory so you can monitor the HTTP request being made.

**Comment by bryant1410** [comment]
Ok, here is the thing. An email sending event in Intercom is triggered via the integration with Segment. This event should be done asap, avoiding wasting time waiting for 20 events or 30 seconds to happen (the default flush in Android SDK). At the same time it could happened that the user loses connectivity, so it would be good to know whether the events upload was successful in order to tell the user so.

**Comment by f2prateek** [comment]
Makes sense, for your best option for now is to use a custom connection factory so you can monitor the HTTP request being made.

**Comment by f2prateek** [comment]
Actually one more thing, even though the device might upload the event to our servers, sending from our servers to integrations (e.g. intercom) is still async, so there might still be a delay between after the devices *completes* the http request before the event is sent, so you can never get a 100% guarantee when an event will be delivered to Intercom.

**Comment by bryant1410** [comment]
Ok, good to know.
