### ISSUE TITLE
Limit identify calls with identical traits.

### ISSUE THREAD

**Issue by NightlyNexus** [segmentio/analytics-android#535]
I'd like to call identify a lot to keep my user traits updated.
But, I'd rather not waste the network calls when no traits have actually changed.

I could maintain my own cache of the traits, but I'm wondering if this library could help me avoid that added complexity.

So, API request:
An option to no-op the identify call if the Traits cache is equal to the Traits passed in.
or
An API to access the Traits cache created by this library.

**Comment by f2prateek** [comment]
> I'd like to call identify a lot to keep my user traits updated.
> But, I'd rather not waste the network calls when no traits have actually changed.

I think maybe the usage you have in mind is something we haven't considered.

Typically we tell people to call identify on certain actions rather than unconditionally. Actions such as:

1. Signing up
2. Logging in
3. Filling some form

I think in these cases typically there isn't a high likelihood that the traits are already cached (maybe in 3 but rare still). Could you describe when you call identify in your app that sometimes is identify with the same data as before?

> An option to no-op the identify call if the Traits cache is equal to the Traits passed in.

I think that can lead to surprising behaviour. If you call `analytics.identify()` I think people reasonably expect it to show up, like how if you'd call `analytics.track()` with the exact same arguments we'll still send a new event (they're not quite the same but still).

Another reason to not do that would be what if you've turned a new tool on. If we are deduping these by contents, the new tool might never receive an identify call.

> An API to access the Traits cache created by this library.

IIRC, you should be able to use `Analytics.with(context). getAnalyticsContext().traits()`.

**Comment by NightlyNexus** [comment]
Ah, good points. Thanks.
AnalyticsContext.traits() is probably what I currently want...

>Could you describe when you call identify in your app that sometimes is identify with the same data as before?

I'd like to associate traits like "Is location services enabled?", "Is an accessiblity service enabled?", and "Is a wearable device connected?" with my users. These traits may change without real hooks into their changes, so I was thinking just best-effort run identify when the window opens.

Is there a better way to do what I'm thinking?

**Comment by f2prateek** [comment]
I think you might not want those as user traits. A user might have multiple devices with conflicting values that clobber each other.

What tools are you using to look at/analyze these? If this is in a warehouse, sending those in the context seems to be the best way to do that. Otherwise as event properties should also be ok.

**Comment by NightlyNexus** [comment]
Yeah, in a warehouse (Redshift).

What do you mean by "sending those in the context?"

**Comment by f2prateek** [comment]
Context is like properties but applies to all event types — https://segment.com/docs/spec/common/#context. This is where we collect information like the application version, network status, etc. You can set custom fields using https://segment.com/docs/sources/mobile/android/#context.

**Comment by NightlyNexus** [comment]
Aah, yeah, nice.
These things like "Is location services enabled?" are much more like the locale and os version than user traits.

I wasn't able to convince my data people (I'll have to do an equals check on the `AnaltyicsContext.traits()`), but that's good to keep in mind for the future.

Thanks a ton!
