### ISSUE TITLE
Duplicate analytics client exception is raised after having reset the client

### ISSUE THREAD

**Issue by lynfogeek** [segmentio/analytics-android#538]
I am facing an issue trying to instantiate an Analytics instance, with (possibly) a `writeKey` which was previously used.

Once I call `analytics.reset()`, I expect to be able to build a new instance of `Analytics` with the previously used `writeKey`, without raising an exception.
Instead, this exception is raised:
https://github.com/segmentio/analytics-android/blob/639eedffb24b2af3d1c6500cf5b98c548843526c/analytics/src/main/java/com/segment/analytics/Analytics.java#L1294-L1298

The same use of the "analytics-ios" SDK works.

Could you consider a way to better reset the internals of the framework? or reuse an existing `INSTANCE` silently? The current APIs don't seem to allow me to do this.

**Comment by f2prateek** [comment]
What you're looking for is analytics.shutdown(). Reset will only clear local storage, it's meant for cases like user logging out of your app and a new user logs in.

This works in analytics iOS because it's a library that doesn't support multiple writeKeys (at least not properly) at the moment.

**Comment by xiaogegexiao** [comment]
Hi @f2prateek I'm having the same issue here.

I'm using 
`analytics = new Analytics.Builder(appContext, Environment.SEGMENT_WRITE_KEY)
                    .trackApplicationLifecycleEvents()
                    .build();
 Analytics.setSingletonInstance(analytics);`
When app user logged in.

And when the app user logged out. I called these
`Analytics.with(appContext).flush();
  Analytics.with(appContext).reset();`

And then after new user logged in, I tried to call the same code as above. I crashed and said

> Duplicate analytics client created with tag:

I'm wondering is 

> reset
enough, or I should also call 

> shutdown
Thanks

**Comment by f2prateek** [comment]
Yes, you need to call shutdown() if you are going to create a new Analytics object instance.

**Comment by xiaogegexiao** [comment]
Yeah, I used shutdown() after the user logged out.
But unfortunately, it came with error 

> UnsupportedOperationException: Default singleton instance cannot be shutdown.

I think it is because of I used 

> Analytics.setSingletonInstance(analytics);

But, if I don't use setSingletonInstance, am I able to log user information. I did this according to https://segment.com/docs/sources/mobile/android/

I guess I don't need to set the global singleton necessarily, as long as I hold the analytics instance reference?

**Comment by f2prateek** [comment]
Yes, you can't call shutdown the singleton instance.

You should only create new instances of the Analytics object if you are using multiple writeKeys. 

It doesn't sound like you need multiple write keys for your use case. Hence I suggest you implement it as the following:

1. in Application.onCreate

```
Analytics analytics = new Analytics.Builder(appContext, Environment.SEGMENT_WRITE_KEY) .trackApplicationLifecycleEvents() .build(); Analytics.setSingletonInstance(analytics);
```

2. When user logs out

```
analytics.reset();
```

This way you don't need to worry about calling shutdown or creating multiple instances, and can still use the global instance.

**Comment by sergiomarquesmoura** [comment]
This issue makes it hard to integrate the SDK in an Android library, since you don't have an Application class to call the shutdown(). Definitely ignoring the instance in case one using the same tag is already stored would be a better option for these non-application use cases

**Comment by f2prateek** [comment]
Hmm... I'm not sure I follow. If you're a library then you shouldn't be using the singleton instance anyway as that should be reserved for the host application.

**Comment by sergiomarquesmoura** [comment]
That's right, but even without setting the singleton instance, apparently it's still possible to get the duplicate analytics client exception

**Comment by f2prateek** [comment]
Yes - the exception is to remind you to not create multiple instances with the same key.

You should pass around the analytics object in your library wherever you need to use it rather than creating a new one on demand. Call shutdown on this instance when you're done with it so if you do need to create a new one, the previous one is shut down.

**Comment by iadcg** [comment]
How do you solve this in the react native part?
Is this enough?

```
try {
  segment.setup(Config.SEGMENT_WRITE_KEY, {
    // Record screen views automatically!
    recordScreenViews: true,
    // Record certain application events automatically!
    trackAppLifecycleEvents: true,
  });
}
catch (e) {
 console.error(e.message);
}
```

**Comment by sergiomarquesmoura** [comment]
> You should pass around the analytics object in your library wherever you need to use it rather than creating a new one on demand. Call shutdown on this instance when you're done with it so if you do need to create a new one, the previous one is shut down.

@f2prateek Being a library, and assuming we have no singleton-related conflicts with the host app (I solved them in a different way), this is what I'm trying to do, and I'm still getting the exception of multiple singletons:
```
@Provides
    open fun provideAnalyticsApi(context: Context): Analytics {
        try {
            val analytics = Analytics.Builder(context, KEY).build()
            Analytics.setSingletonInstance(analytics)
            return analytics
        } catch (e: IllegalStateException) {
            Analytics.with(context).reset()
            return provideAnalyticsApi(context)
        }
    }```

I would expect this code to always return me an Analytics object with KEY. However, apparently the reset() is not clearing the singleton (I read the source code). Also, you cannot call `setSingletonInstance(null)` when a singleton is already defined. The reason I need the singleton is so that I can call `Analytics.with(context)` to try to reset it in case we see multiple initialisations.

So in my opinion, either the `reset()` call shout set `singleton = null` or the `setSingletonInstance(null)` should be allowed.

Finally, your suggestion of passing the object around wherever needed doesn't seem very nice from the point of view of an Android library with many screens where each one of them must receive this object. It forces us to create interfaces to pass the object around in between each 2 screens, and almost impossible to use together with a dependency injection framework.

**Comment by santhoshrm** [comment]
@f2prateek  I am facing similar crash where we want two different instances of Analytics,
My use case is I have android device which can be controlled by companion device.

Based on type of companion device used we want to send to different destination

we do something like this 
```
  if (analytics != null) {
            analytics.shutdown();
   }
    analytics = new Analytics.Builder(context, segmentKey)..... 
```

and use analytics.track or analytics.identify as needed. 

We are seeing below crash. Any suggestions?
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
       at com.segment.analytics.SegmentIntegration.submitFlush(SegmentIntegration.java:314)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by varun-firminiq** [comment]
@f2prateek I am facing app crash - '**Duplicate analytics client created with tag: If you want to use multiple Analytics clients, use a different writeKey or set a tag via the builder during construction**'. In fact, I looked into this matter by following the official documentation of Segments, then I found that there are some functions to reset the Analytics data or we can flush it by using reset() or flush() respectively. Once I call analytics.reset() or analytics.flush(), I expect to be able to build a new instance of Analytics with the previously used writeKey, without raising an exception. Instead, I got the same exception or sometimes "**UnsupportedOperationException: Default singleton instance cannot be shutdown**". The same use of the "analytics-ios" SDK works. The reset() is not clearing the singleton (I read the source code). I thought it is because of I used Analytics.setSingletonInstance(analytics); in Application Class in order to rely upon the globally accessible instance so that I can track screen and event anywhere using Analytics.with(Context). The reason I need the singleton is so that I can call Analytics.with(context) to try to reset it in case we see multiple initializations. But, I removed the idea of setting instance to global in order to verify the changes, but again I got the exception - use a different writeKey to create Analytics client. Then, I thought that our requirement is to write multiple keys, then we have to create multiple instances of Analytics client. Then, I thought of setting _Analytics.setSingletonInstance(null)_ before proceeding with building any Write_Key in Analytics. But, you cannot call _setSingletonInstance(null)_ when a singleton is already defined. By facing all these worst scenarios, I think of saving Analytics Key in shared preferences, and then comparing it with the key fetched according to the country code selected from the drop down menu. It they are different then only we should allow to write it in Analytics Builder using tag during construction. This is what the first exception says all. In this way, I got rid of unwanted exceptions for the time being as there are same keys in each build mode(Prod/Debug/Staging) for each country. But, I would like to get a better solution when ever I will get different keys according to the country to write them in Analytics Builder as I need to track different data for each country and cannot share data in different region to prevent data violation. I shall be waiting for a favorable reply.

**Comment by f2prateek** [comment]
The singleton cannot be changed (see the previous comment https://github.com/segmentio/analytics-android/issues/538#issuecomment-448355827). I would suggest reaching out to our support team if you need additional help https://segment.com/contact/.

**Comment by priyanshnama** [comment]
using the code below to integrate the sdk
```
String segment_write_key = getResources().getString(R.string.segment_dev_writekey);
WebEngageConfig webEngageConfig = new WebEngageConfig.Builder()
        .setDebugMode(true)
        .build();
Analytics analytics = new Analytics.Builder(this, segment_write_key)
        .trackApplicationLifecycleEvents() // Enable this to record certain application events automatically!
        .logLevel(Analytics.LogLevel.VERBOSE)
        .use(WebEngageIntegration.FACTORY.withWebEngageConfig(webEngageConfig))
        .build();
Analytics.setSingletonInstance(analytics);
```

it says Singleton instance already exists.
the problem is at the last line setSingletonInstance().
