### ISSUE TITLE
Application Opened is not tracked properly

### ISSUE THREAD

**Issue by PedramVeisi** [segmentio/analytics-android#542]
Hi,

I enabled automatic tracking of lifecycle events and everything works fine except "Application Opened". Based on the [docs](https://segment.com/docs/spec/mobile/#application-opened) 

> This event fires when a user launches or foregrounds your mobile application after the first open.

And it should have a "from_background" property. I see a different behavior. The event is fired only if the app is closed (not when foregrounded). Also, the properties being sent with this event are "version" and "build".

**Comment by f2prateek** [comment]
This is intentional. The properties are meant to be what you *should* send if you implement the event manually. There's no way for us to get this information in a generic way easily for all our customers, so those fields are not collected.

It is intentional to collect version and build as well. I'll update the docs for that.
