### ISSUE TITLE
delay "application Installed" until user Identify?

### ISSUE THREAD

**Issue by littlehome-eugene** [segmentio/analytics-android#606]
It seems Application Installed happens first before we can do `identify` with a unique user id. 

Is it possible to delay `Application Installed` until we do `Identify` ? 
Or is this already taken care of?

**Comment by segmenttest** [comment]
hi @littlehome-eugene, 

You are exactly right --- when you have [Lifecycle events enabled](https://segment.com/docs/spec/mobile/#lifecycle-events), on first app open both **Application Installed** and **Application Opened** will be triggered - containing an anonymousId but not userId (user has not yet been identified). 

This is how we recommend using these lifecycle events. 

If you would like to adjust behavior, feel free to disable Lifecycle events and trigger the events on your own! 

If you have any followup questions around implementation or general best practices, feel free to reach out to our team at https://segment.com/help/contact/.

**Comment by TeresaNesteby** [comment]
Hi @littlehome-eugene, 

You are exactly right --- when you have enabled [Lifecycle events](https://segment.com/docs/spec/mobile/#lifecycle-events), on first app open, both **Application Installed** and **Application Opened** events will be triggered with an associated anonymousId but no userId (as the user has not yet been identified). 

This is expected behavior and follows our recommended best practices. 

If you have a use case in which you'd like to adjust this behavior, simply remove Lifecycle events, and manually trigger these events with the information you'd like. 

If you have any additional questions around implementation or best practices - let us know -- at https://segment.com/help/contact/.
