### ISSUE TITLE
Use different Segment Keys for different App environment

### ISSUE THREAD

**Issue by pagrawal1407** [segmentio/analytics-android#724]
Hello, I'm trying to add a functionality for Segment Analytics. Whenever the app environment is switched to "Test", I want the segment events routed to a different server (or data base? Not sure what is the correct word). For that, I am trying to use different key if it's not production environment. But the issue is, when the app is installed, it always starts in production environment and initializes the Analytics SDK accordingly with PROD key. But when I try to switch the environment, I get the exception: `Caused by : java.lang.IllegalArgumentException: writeKey must not be null or empty.` or `Caused by: java.lang.IllegalStateException: Singleton instance already exists..`

I am not sure how to clear the previous Singleton instance and add a new one with a different key.

I am using this code to initialize the Analytics SDK

`Analytics analytics = new Analytics.Builder(application.getApplicationContext(), segmentKey)
                        .use(AppsflyerIntegration.FACTORY)
                        // Enable this to record certain application events automatically!
                        .trackApplicationLifecycleEvents()
                        // Enable this to record screen views automatically!
                        .recordScreenViews()
                        .trackAttributionInformation() // Install Attributed eventx
                        .build();
                // Set the initialized instance as a globally accessible instance.
                Analytics.setSingletonInstance(analytics);`

**Comment by prayansh** [comment]
@pagrawal1407 This is more of an implementation questio. Switching between write-keys should be as easy as changing the write-key you provide while initialising the segment sdk. I have provided a code snippet that you can refer to for the same.
```java
String segmentKey = "Your Prod Write Key";
if (BuildConfig.DEBUG) { // There are probably other ways to check if its a test environment  
      segmentKey = "Your Test write key";
}
Analytics analytics = new Analytics.Builder(application.getApplicationContext(), segmentKey)
                                  .use(AppsflyerIntegration.FACTORY)
                                  .trackApplicationLifecycleEvents()
                                  .recordScreenViews()
                                  .trackAttributionInformation()
                                  .build();
Analytics.setSingletonInstance(analytics);
```

Also to note: `Analytics.setSingletonInstance(analytics);` can only be called once per lifetime of an application. You cannot attach multiple analytics instances to the singleton instance (Thus causing the `Caused by: java.lang.IllegalStateException: Singleton instance already exists..` error).

Please reopen the issue if the above suggestion does not work for you
