### ISSUE TITLE
java.lang.IllegalStateException when initialising Segment

### ISSUE THREAD

**Issue by rhydiant** [segmentio/analytics-android#725]
We're seeing the following crashes on some devices:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3448)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3595)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2147)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7814)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)
Caused by: java.lang.IllegalStateException: 
  at com.segment.analytics.Analytics$Builder.build (Analytics.java:1349)
  ...
```

When the following setup is executed:
```
 Analytics.setSingletonInstance(Analytics.Builder(context,
    "[key_ommited]")
     .trackApplicationLifecycleEvents()
     .flushInterval(1, TimeUnit.SECONDS)
     .build());
```

So far effected the following devices:
 - Samsung Galaxy A11 Android 10 (SDK 29)
 - Samsung Galaxy S7 edge Android 8.0 (SDK 26)

Using `com.segment.analytics.android:analytics:4.+`

**Comment by ianjsikes** [comment]
I am getting a similar issue. I have a React Native app so I am not using this library directly, but as a dependency of `@segment/analytics-react-native`. The IllegalStateException is `Method addObserver must be called on the main thread`

**Comment by ianjsikes** [comment]
The issue appears to be due to a change in [`androidx.lifecycle`](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.0-alpha06) introduced in version `2.3.0-alpha06`.

> LifecycleRegistry now verifies that its methods are called on main thread. It was always a requirement for lifecycles of activities, fragments etc. An addition of observers from non-main threads resulted in hard to catch crashes in runtime. For LifecycleRegistry objects that owned by your own components, you can explicitly opt out from checks by using LifecycleRegistry.createUnsafe(...), but then you have to ensure that a proper synchronization is in place when this LifecycleRegistry is accessed from different threads (Ie7280, b/137392809)

I am guessing that the issue is appearing for me because of another library that has a transitive dependency on `androidx.lifecycle` version `2.3.0-alpha07`.

**Comment by cristeahub** [comment]
I am encountering the exact same issue after upgrading my Stripe SDK from 10.x to 16.x. One of the changes in that huge jump is that the StripeSDK migrated fully to AndroidX, which I suspect is the culprit for me receiving this issue now.

I am using the react native wrapper, so I opened an issue there (https://github.com/segmentio/analytics-react-native/issues/255), hopefully to get this problem a bit more attention.

Any workarounds or other fixes shared by anyone is greatly appreciated.

**Comment by prayansh** [comment]
> LifecycleRegistry now verifies that its methods are called on main thread.
This seems to be the crux of the issue, though I am not sure why analytics is not being invoked on the main thread.

I have not been able to reproduce this issue, so all of this is theoretical but we can potentially circumvent this error by using the `experimentalUseNewLifecycleMethods(false)` builder option. 

@cristeahub Currently on **analytics-react-native** there is no direct way to set this builder option, so we will need to add that change. In the meanwhile, to confirm my theory (since i havent been able to reproduce the issue), you could in development try the following change: In your local `node_modules` make a change [here](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt#L150) and add the following line `builder.experimentalUseNewLifecycleMethods(false)`

**Comment by cristeahub** [comment]
> @cristeahub Currently on **analytics-react-native** there is no direct way to set this builder option, so we will need to add that change. In the meanwhile, to confirm my theory (since i havent been able to reproduce the issue), you could in development try the following change: In your local `node_modules` make a change [here](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt#L150) and add the following line `builder.experimentalUseNewLifecycleMethods(false)`

Amazing, this fixed it! You are my hero, this has been keeping me up at night!

I have some internal processes to apply this patch locally. Will you create a pr on the react-native project to add this?

**Comment by prayansh** [comment]
awesome! good to know that it worked for you. I will try to make a PR to the react-native project ASAP

**Comment by prayansh** [comment]
This sho
