### ISSUE TITLE
How to send the Application Crashed event

### ISSUE THREAD

**Issue by pablobaldez** [segmentio/analytics-android#808]
I'm checking the [documentation](https://segment.com/docs/connections/spec/mobile/#application-crashed) regarding to the lifecycle events and it's not clear to me **how** can I send the "Application Crashed" event to segment.

It seems that it is not an event triggered by default, so I would like to know if there is an easy way to identify when the app is crashed and how to send it to my segment dashboard.

Could you help me?

**Comment by wenxi-zeng** [comment]
you should be able to do it by implementing `UncaughtExceptionHandler ` (see [here](https://stackoverflow.com/questions/37256595/how-to-have-a-callback-for-when-a-crash-occurred-while-using-crashlytics-sdk)) and do a track call in `uncaughtException`

**Comment by pablobaldez** [comment]
I tried the recommended approach but no event is sent to segment.
It seems that after the app crashes the segment stops to send events. 

Here is the example code:
```kotlin
class MyApplication : Application() {

    private val segment by inject<AnalyticsManager>()
    private lateinit var defaultUncaughtExceptionHandler: Thread.UncaughtExceptionHandler
    private lateinit var customUncaughtExceptionHandler: Thread.UncaughtExceptionHandler

    override fun onCreate() {
        super.onCreate()
        defaultUncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()
        customUncaughtExceptionHandler = Thread.UncaughtExceptionHandler { thread, e ->
            segment.track("any event")
            analyticsManager.segment.segment.flush()
            defaultUncaughtExceptionHandler.uncaughtException(thread, e)
        }
        Thread.setDefaultUncaughtExceptionHandler(customUncaughtExceptionHandler)
    }
```

Am I doing something wrong?

**Comment by wenxi-zeng** [comment]
I'd suggest:
1. put a logger in the handler, see if the handler actually gets called when app crash
2. if the handler is called, make sure your segment instance is still alive at the time the handler get called.
3. otherwise, nothing we can do here. it's an os level issue, not our sdk can address.

also, since you're using kotlin, it's strongly recommended to upgrade to our [analytics-kotlin](https://github.com/segmentio/analytics-kotlin) library. it's 3x more performant with half of the resources. check out the performance benchmarks [here](https://segment.com/blog/sdk-performance-improvements/).
