### ISSUE TITLE
Do we need to upgrade integration SDKs (Device ID Collection Circumvents Google Play User Data Policy)

### ISSUE THREAD

**Issue by csantarin** [segmentio/analytics-android#809]
From https://github.com/segmentio/analytics-android/issues/801#issuecomment-1152491861:

> if you're using any device mode integration, you probably will see this warning even if you updated to `4.10.4`. that's because the integration sdks internally uses an old version of analytics-android. a fix to that is underway.

@wenxi-zeng So, we're using Segment `4.9.3` and after reading this, it suggests we'll have to do the same for the rest of the integrations that we use. This is what we have:

- [Segment <> Amplitude `3.0.3`](https://github.com/segment-integrations/analytics-android-integration-amplitude/blob/3.0.3/build.gradle#L52) (Segment `4.3.1`)
- [Segment <> AppsFlyer `6.1.1`](https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin/blob/6.1.1/app/build.gradle#L27) (Segment `4.+`)
- ...**and** we have a Segment middleware usage for AppsFlyer.

Does that mean we'll have to also upgrade these integrations, especially the Amplitude one? According to the Gradle version conflict resolution strategy, AFAIK, it will choose the latest version of Segment, even when we don't upgrade.

**Comment by wenxi-zeng** [comment]
hey @csantarin, yes you're right. you'll need to do the same for the integrations. for amplitude, please upgrade to the latest `3.1.2`. for appsflyer, since it's not an sdk maintained by segment, you'll have to raise an issue on their repo asking them to release a new version. the `+` sign only pulls the latest sdk at compile time. it won't change anything in a compiled/published sdk. but if you're using their source code, that's a different story.

**Comment by wenxi-zeng** [comment]
sorry, I missed your point. regarding conflict resolution, we also thought that gradle will choose the latest one, but we had customer getting warnings because of the integrations use the old analytics sdk. so we had to make new release for the integrations.
 
we have contacted Appsflyer team and requested them to make a new release. I checked the release date of the most recent Appsflyer was end of Jan, which is based on `4.10.2`. it already addresses the google policy issue. so it should be ok to use.

**Comment by csantarin** [comment]
@wenxi-zeng Sounds good!

Last question: does upgrading Segment and the integration still guarantee we get the same data pre-upgrade? From the Segment dashboard, I've seen no difference so far. I looked up the official docs; there's no indication of any data loss there, too.

**Comment by wenxi-zeng** [comment]
@csantarin yes. the device id would be different, since we're no longer collecting android id or any sort of id can trace to the physical device. but besides that, the data are all the same

**Comment by csantarin** [comment]
@wenxi-zeng got it. thanks!
