### ISSUE TITLE
Can not init Segment for 4.11.2

### ISSUE THREAD

**Issue by Joemiao120** [segmentio/analytics-android#835]
Hi Team, I'm using the Android Segment SDK `4.+`, it works fine before today, but today it stops working, and I got one exception for initing the Segment. The exception is:

> Tried to obtain display from a Context not associated with one. Only visual Contexts (such as Activity or one created with Context#createWindowContext) or ones created with Context#createDisplayContext are associated with displays. Other types of Contexts are typically related to background entities and may return an arbitrary display.

I found today you guys release a new version 4.11.2, so could you guys have a look at this issue, and help me out?

**Comment by bigoloo** [comment]
Same issue here!

**Comment by TylerMcCraw** [comment]
Actually, padding the Activity Context won't work either because the Analytics class expects a context of type Application.
See here: https://github.com/segmentio/analytics-android/blob/dcc76afb5802e43c281a1173302a7e7250e41750/analytics/src/main/java/com/segment/analytics/Analytics.java#L1114

I don't understand how this fix worked.
@wenxi-zeng were you able to test this fix on Android 11+?
If so, what is the recommended solution to avoid the exception being thrown that @Joemiao120 mentioned?

**Comment by wenxi-zeng** [comment]
thank you all for reporting this issue. we'll get this fixed today. in the meanwhile, please use `4.11.1` instead

**Comment by wenxi-zeng** [comment]
hey all, this issue is fixed in `4.11.3`. please have a try. sorry for the inconvenience. we have an adnroid 10 device was labeled as android 11, which gives false positive test result on the previous release.
